### ISSUE TITLE
Integrate with Fabric Crashlytics

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#110]
Because the handling of dSYMs for Firebase Crash Reporting is rather troublesome and Firebase already suggests migrating to Crashlytics, as it will replace FCR "soon", integrating Crashlytics into the app might be a good idea.

**Comment by Fenrikur** [comment]
Postponed until after EF23, as FCR does seem to work for now.

**Comment by ShezHsky** [comment]
Fixed in f4ee1fd5e4cf590e710b307cee26197bbff88f20
