### ISSUE TITLE
Open links in Safari view instead of launching Safari

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#122]
All links (e.g. on dealer details and knowledge entries) are opened by launching Safari as an external app.
This behaviour should be replaced by opening them in an Safari view in-app to make having a quick glance at links less disruptive.

**Comment by ShezHsky** [comment]
Added in 4275dd85a7f2b537afcacdfc24e91a42a6677748. If an app can open the link we'll deep link the user there instead, otherwise use `SFSafariViewController`.
