### ISSUE TITLE
Forward swipe gestures to embedded WebView on game

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#123]
Swiping to the right will return the user to the "More" VC instead of taking a step back in the WebView's history.

**Comment by ShezHsky** [comment]
Closing as this is correct behaviour - the `UINavigationController` is responding to the gesture as expected. If we want to use this gesture, the game should be hoisted into a `SFSafariViewController` that we show modally w/ an appropriate 'Done' button. 

If we want navigation within the game, we should add 'Back' and 'Forward' buttons in the game UI.
