### ISSUE TITLE
Login will not be persisted when logging in again after hitting Sign Out

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#127]
When the user signs out, any further login attempts will not be persisted until the app has been restarted.

Steps to reproduce:
1. Perform login
2. Check whether login was persisted by getting back to the News page
3. Log out via messages view
4. Log in again
5. Switch back to the News page
-> You will be signed out.

Details:
When signing out again while viewing messages in volatile login state, the app will fail to delete credentials from the key store, since they have not been persisted there in the first place.

**Comment by ShezHsky** [comment]
Fixed in 807f45380a24a1ae6d1c6408c21d15aa0487dfb9
