### ISSUE TITLE
Progress bar on tab bar fails to disappear immediately after finishing the sync process

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#133]
When the app refreshes on launch, the progress bar on top of the tab bar stays visible even after the completion delegate has been called as apparent from the green whistle at the top of the screen.
It will disappear after approx ten seconds though.

Verified on iPhone 6s (iOS 10.3.3)

**Comment by ShezHsky** [comment]
Closing as the new UI makes this issue non-reproducible
