### ISSUE TITLE
API Method Change: Message Read Receipt

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_ios#145]
See: https://app.eurofurence.org:40000/swagger/v2/ui/#/Communication/ApiV2CommunicationPrivateMessagesByMessageIdReadPost

**Previous** version of the API expected no content (empty body POSTed), **New** version expects `true` to be the sent in content body. (This is to accomodate Android, as their swagger generated code is buggy with null payloads).

You can use `EurofurenceAppBotTest` on Telegram to test send PMs to you (use `/badgeChecksum` to get the full badge no of yours; then use `/pm` to send the message.)

**Comment by ShezHsky** [comment]
Reopening as didn't realise saying "Resolves x" also closes a ticket 🙃

Need to do some manual verification on 726d547 however this requires fudging the app endpoints to point to the test API as #144 is still in progress

**Comment by ShezHsky** [comment]
Fix seems to work! Please reopen if this is not the case.
