### ISSUE TITLE
Support Markdown content in announcements, knowledge base entries and events

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#154]
Modules to which Markdown support needs to be added:
- [x] Announcement Detail
- [x] Announcements
- [x] News (Announcements)
- [x] Knowledge Detail
- [x] Event Detail

**Comment by Fenrikur** [comment]
The API currently provides the following data which may contain content formatted using Markdown:
- Announcements
- Events
- Knowledge Base
