### ISSUE TITLE
Clean up settings page

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#17]
The settings page should be cut down to contain only functional and relevant settings with the debug options either being entirely unavailable in release builds or hidden behind some kind of easter egg.

**Comment by ShezHsky** [comment]
- Hidden the debugging settings for the release configuration in d5b9ee40b6ecea45cbe5a644e213fdf734419808
- Performed some additional tidy up in 40642a7b4445a6d22a08d69aec6601c6cc2be2b5

Is there anything else in this issue you wanted to address @Fenrikur?

**Comment by ShezHsky** [comment]
Closing this as it appears done, if we find any more issues with the settings page we can spawn new issues for them.
