### ISSUE TITLE
Show event icons based on tags from response

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#171]
Bound to scenes

- [x] Sponsor
- [x] Super sponsor
- [x] Kage icons
- [x] Art Show
- [x] Dealers Den
- [x] Main Stage
- [x] Photoshoot

Data propagated from model

- [x] Sponsor
- [x] Super sponsor
- [x] Kage icons
- [x] Art Show
- [x] Dealers Den
- [x] Main Stage
- [x] Photoshoot

Shown in event detail

- [x] Sponsor
- [x] Super sponsor
- [x] Kage icons
- [x] Art Show
- [x] Dealers Den
- [x] Main Stage
- [x] Photoshoot

**Comment by Pinselohrkater** [comment]
That can be obtained via `Event.Tags`

Here's the code in Android that maps tags to Glyphs and Texts (that are shown in the event detail):

See https://github.com/eurofurence/ef-app_android/blob/528c869a308fef20a1b4b363415c81398bed7764/app/src/main/kotlin/org/eurofurence/connavigator/database/Db.kt#L458 

![screenshot_1533018550](https://user-images.githubusercontent.com/13329381/43580718-b842e714-9656-11e8-8118-8b84c0288404.png)
![screenshot_1533018545](https://user-images.githubusercontent.com/13329381/43580719-b85c87aa-9656-11e8-8e12-6a9ae72e7bb2.png)

**Comment by ShezHsky** [comment]
Renaming ticket to reflect additional icons to ensure work
