### ISSUE TITLE
Banner image on home is cropped

### ISSUE THREAD

**Issue by Requinard** [eurofurence/ef-app_ios#179]
The banner on the home screen for the ipad is cropped, cutting out some of the text

![image](https://user-images.githubusercontent.com/5537850/43844083-3381ae5c-9b29-11e8-8ff7-f9b171048f62.png)

**Comment by ShezHsky** [comment]
Fixed by @Fenrikur in e3e6d3b18658e1a5b3cc05365b906bec57601fec
