### ISSUE TITLE
Overlay for debug features

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#18]
Certain debug features may require direct access from any view. It should therefore be possible to open a non-modal debug overlay (e.g. using 3D Touch).
Optional: Moveable overlay; multiple sections; pop-up offering choice of different overlays

Debug features may for example include changing the current in-app time via TimeService, simulating push notifications, manually induced crashes, …

**Comment by ShezHsky** [comment]
Fixed in 8cb2563b8b5fde9f7ce3859bc2241e5b021cc408, double tapping the app 5 times opens the window
