### ISSUE TITLE
Update help text on login form

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_ios#184]
**Old:**
If you do not have access to them, come to ConOps or Registration. They can help you with an alternative login. Please bring your badge and a valid legal form of identification.

**New:** - changes in **bold**
If you do not have access to them, come to **our registration desk or security office**. They can help you with an alternative login. Please bring your badge and a valid legal form of identification.

**Comment by ShezHsky** [comment]
<img width="539" alt="screen shot 2018-08-14 at 12 08 44" src="https://user-images.githubusercontent.com/12624320/44088397-dd01ae24-9fba-11e8-804b-eb6c4cb485b5.png">
