### ISSUE TITLE
Transition to CID backed model

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#191]
Continue to use last years API by default. When enabling the latest API via a toggle, use the appropriate debug and release APIs for EF25.

**Comment by Pinselohrkater** [comment]
Keep in mind that, starting with EF25, the backend introduces the CID related logic.

See: https://wiki.eurofurence.org/doku.php?id=team:it:app:backend:cid

**Comment by ShezHsky** [comment]
Few tasks to do here that will use the new CID:

- Inject an API factory in place of an API object, that can produce an API for a given CID
- Add a URL-providing implementation for CIDs, V2API won't need to change much
- Check the app-backed CID matches the identifier from the sync response, otherwise do not proceed past the preload module
- Store the 'current' CID somewhere, and use that to purge the data store in the event the app-baked CID is different (avoiding local store discrepancies). No CID implies it's the EF24 app, for lack of other info
