### ISSUE TITLE
Menu Changes: Url Scheme, Collect'em All, "Additional Services"

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_ios#196]
- [x] 1. Implement new Url Scheme builder with pass-through auth support
- [x] 2. Adjust existing Collect'em All target URL
- [x] 3. Create new menu item "Additional Services"

**1. New Url Scheme / Endpoints for pass through auth**

Starting with EF25, all app components that we put into the companion web-app now support deep linking with auth pass-through, with the following convention:

`https://app.eurofurence.org/{$CID}/companion/#/login?embedded=true&returnPath={$REDIRECT_URL}&token={$AUTH_TOKEN}`

$CID is the Convention Identifier, e.g. EF25
$REDIRECT_URL is the route within the companion app to navigate to, e.g. "/" or "/collect"
$AUTH_TOKEN is the users auth token (eyXXX.XXX.XXX)

_Example:_ (Not working due to sample token.)
https://app.eurofurence.org/EF25/companion/#/login?embedded=true&returnPath=/collect&token=eyJhUGX0dC0Fxxxxxx

**2. Adjust existing Collect'em All target URL**

Collect'Em All should use the new Url Scheme, and is located on the '/collect' route. When opening it, the URL the user is redirected to (this year) would look like:

https://app.eurofurence.org/EF25/companion/#/login?embedded=true&returnPath=/collect&token=eyJhUGX0dC0Fxxxxxx

**3. Create new menu item "Additional Services"**

Add a new menu item (ideally just 'after' Collect'Em All) that is called "Additional Services". Android will use a 'book' type icon. The purpose of this is to just send the user to the companion web-app where we can provide all sorts of native-app independent features, year by yar.

Clicking on it would again use the new Url scheme and redirect them to the '/' route.

https://app.eurofurence.org/EF25/companion/#/login?embedded=true&returnPath=/&token=eyJhUGX0dC0Fxxxxxx

_All endpoints/URLs already exist & are valid for this year and can be tested against._

**Comment by ShezHsky** [comment]
All closed off in #214
