### ISSUE TITLE
Integrate Firebase for Crash Reporting

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#22]
All crashes should be reported via an online platform to keep track of bugs in testing as well as release branches.
As Firebase will be the way to go for push notifications according to #8, it would be the easiest way to prepare the integration at this stage already.

**Comment by ShezHsky** [comment]
Integrated Firebase into the app, will need to work out a nice way of automatically submitting symbol files up when we produce release candidates (could be something to integrate w/ Travis)
