### ISSUE TITLE
Add a proper loading screen and wait for initial loading task to complete

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#23]
Launchscreen should receive some actual content and should be displayed until the app has finished loading data from the persistence layer and the news view has been properly populated.

On Windows Phone, this is currently handled by showing a loading animation along with a randomised quote.

**Dependency of:** #24

**Comment by ShezHsky** [comment]
It looks like this has reproduced the issue seen in #47 - there's no longer any data shown in the app, and the view models appear to be empty. Eagerly loading the data seems to be cause of this, as if the bindings on the view models have been broken (hypothesising).

**Comment by ShezHsky** [comment]
Splash screen is now shown on launch after witnessing the tutorial, or when the tutorial ends. This is very basic in appearance - created #50 to make it look pretty w/ this years assets.
