### ISSUE TITLE
Notify user before initiating the initial synchronisation

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#24]
Upon first launch, the user should be notified that an initial sync is required which may consume a lot more of data due to image downloads (how much can we approximately expect on that account?).
The view should allow postponing initialisation (closing the app) as well as offer a toggle to allow performing the sync on mobile data as well (should otherwise be restricted to WiFi connectivity).

**Dependency:** #23

**Comment by ShezHsky** [comment]
This screen will be placed at the end of the on boarding process

**Comment by ShezHsky** [comment]
The user now sees the following screen the end of the on boarding process, in which the "Begin Download" button continues to the splash screen to initiate the download.

<img width="432" alt="screen shot 2017-07-09 at 19 10 25" src="https://user-images.githubusercontent.com/12624320/27996473-5dc94638-64da-11e7-902a-9d77414a715e.png">
