### ISSUE TITLE
Settings for download preferences (mobile data vs. WiFi)

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#25]
As mobile data plans may be of limited capacity, the settings page should offer three options catering to this issue:
1. Allow data sync via mobile data
Only textual data received from the Sync endpoint may be synced while on mobile data.
2. Allow image download via mobile data
Images may be downloaded on demand while on mobile data.
3. Allow image sync via mobile data
All images may be downloaded on sync via mobile data.

**Dependency:** #2

**Comment by ShezHsky** [comment]
Closing due to lack of feature request/the toggle in Settings can suffice until demand grows.
