### ISSUE TITLE
Perform all synchronisation tasks in background

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#3]
**Current:** A running sync task is hinted at visually by a UIRefreshControl in the initiating view.
**Intended:** User is notified about successful initiation of sync as well as the successful completion of important subtasks via a toast-like notification or similar mechanism.

**Comment by Fenrikur** [comment]
This would probably best be handled by a BackgroundSynchronisationService which is triggered by views or the sync button and should be observed by a view providing a progress bar visible across all views.

**Comment by ShezHsky** [comment]
Fixed in the referenced commits above. Delegates of the `DataStoreRefreshController` (i.e. the progress view above the tab bar, visible view controller's refresh controls and the apps network indicator) are told when refreshes start/stop and show/hide respectively.
