### ISSUE TITLE
Show alert when initial sync will occur over 3G

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#51]
At the end of the onboarding process the user is told we'll download everything the app needs, and that we recommend doing so over WiFi. In the event they are on 3G and hit the button we should show an alert that reminds them of their data usage, and present an option to allow usage of the app over 3G as well as WiFi.

If they decline/cancel the alert, we should not proceed with the download and leave the final screen of the on boarding process visible for them to transition to a WiFi network.

This ties in to #25

**Comment by Fenrikur** [comment]
It might be nicer to just add a toggle switch "Allow download on mobile", which would mirror the appropriate switch on the settings page.

**Comment by ShezHsky** [comment]
The user will now receive an alert when attempting to begin the download without an active wifi connection. They're able to proceed over cellular if they'd like to.
