### ISSUE TITLE
Events search bar is confusing to use

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#67]
Typing text in the search bar will search on event titles, however for the event scopes to work the search bar has to be empty.

**Comment by Fenrikur** [comment]
Scopes have been removed, so that searches are now always performed on event titles.
Filtering and grouping has been implemented via segmented controls in the nav bar.
Part of efe627ec33f4ccdeb6f59ea1dd2ee5adca082a21
