### ISSUE TITLE
Handle silent refresh data notifications

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#78]
When receiving a notification telling us to reload data, we should handle it in the [`UIApplicationDelegate` protocol method](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application) and perform a reload.

**Comment by Fenrikur** [comment]
Silent refresh will now be handled for push notifications with the custom property `Event` set to `Sync` and `content_available` set to `true`.
