### ISSUE TITLE
Register with Firebase to receive push notifications

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#8]
The app should register itself with Firebase upon launch as well as on login state change in order to receive the respective push notifications for each state.

**Comment by ShezHsky** [comment]
Narrowing the scope of this ticket to just focus on registering the token w/ Firebase, can still verify pushes get through as expected without playing anything else. Can play another ticket to link Eurofurence logins and push tokens

**Comment by ShezHsky** [comment]
Tokens now registered with Firebase, can send notifications using Firebase console.

![photo_2017-07-13_21-08-42](https://user-images.githubusercontent.com/12624320/28185841-cc65d3f2-6810-11e7-9b0e-c08c744f9579.jpg)
