### ISSUE TITLE
Clarify presentation of information for events

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#86]
> Opening an event page, I see the date, location and everything on top. Everything has white text except the location, it's blue and looks like a link, but doesn't do anything. I think it would be helpful to link this to a map that shows where the room actually is, considering the changes we face this year.

We could either:
- Fix the text colour for the location to appear as expected, or
- Link to the room on the map when tapping it

**Comment by Fenrikur** [comment]
Suggested solution implemented in fee1901 is to only highlight the location if it actually links to a map location.

**Comment by Fenrikur** [comment]
Closed until further feedback from testers on next TestFlight.
