### ISSUE TITLE
Investigate why "Wolf Gadgets" is not intractable on dealers map

### ISSUE THREAD

**Issue by ShezHsky** [eurofurence/ef-app_ios#88]
Raising here so we don't forget. May be due to the feed? - They have no map info in their dealers page.

**Comment by Fenrikur** [comment]
From what the API results on /Maps and /Dealers show, there is simply no MapEntry relating to the dealer "Wolf Gadgets" so far. Forwarded to the respective team members responsible for the map.

Bug label removed until this has been proper validated as an actual bug and not only missing data on the backend side.

**Comment by Fenrikur** [comment]
This issue is not an actual bug in the app, but due to the fact that the map is not final and therefore some dealers are still missing in the data available via the API.
