### ISSUE TITLE
Authenticate user against registration system to obtain JWT

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#9]
Users should be able to login using their registration credentials in order to receive (push notifications on) direct messages and potentially future features which require the user to identify against the API.
JWT bearer received upon successful login must not be stored on-device in an unencrypted matter and should therefore best be stored in the users keychain (may allow login sync across devices using the same Apple ID?).

**Dependency of:** #15

**Comment by Fenrikur** [comment]
Suggestion for libraries to implement Keychain support:
https://github.com/jrendel/SwiftKeychainWrapper
https://github.com/matthewpalmer/Locksmith

The latter one seems to allow more granular control, while the former provides an interface not unlike UserDefaults.

**Comment by ShezHsky** [comment]
- Added cell(s) at the top of the announcements page to segue to private messages controller (currently unimplemented except to show login)
- Login fires request to backend, retrieves JWT
- Credential stored in local keychain (no cloud sync), restarting app will keep user logged in as long as token hasn't expired

EF app bot is also picking up the login (for my account on my phone).

<img width="432" alt="screen shot 2017-07-21 at 14 42 08" src="https://user-images.githubusercontent.com/12624320/28466038-e371b076-6e22-11e7-9eae-dfa1a11989d0.png">
<img width="432" alt="screen shot 2017-07-21 at 14 42 12" src="https://user-images.githubusercontent.com/12624320/28466037-e36492d8-6e22-11e7-82e3-e2f2a755cff1.png">
<img width="432" alt="screen shot 2017-07-21 at 14 42 36" src="https://user-images.githubusercontent.com/12624320/28466036-e363718c-6e22-11e7-95ef-b92c72f54918.png">
