### ISSUE TITLE
Implement URL scheme for opening deep-links in the app

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#92]
The web app at https://app.eurofurence.org/web/ provides "Open in App" links following a eurofurence:// URL scheme.
The app should register for handling this scheme and route the user to the appropriate views where applicable.

A proposed schema definition can be found at https://gist.github.com/Requinard/186a22c3578ebd2bd7c1ad460c4ac114, with an alternative being to follow the URL scheme already provided by the backend API at https://app.eurofurence.org/swagger/v2/ui/index.html#/.

**Comment by Requinard** [comment]
https://gist.github.com/Requinard/186a22c3578ebd2bd7c1ad460c4ac114

**Comment by Fenrikur** [comment]
Considering the API at https://app.eurofurence.org/swagger/v2/ui/index.html, we already have a basic, established and agreed-upon scheme for accessing entities provided by the backend, which is documented in Swagger.
Since most of the views in all consuming apps are basically just that – views displaying consumed API entities – we could simply just adopt the scheme that is already there.
The currently available GET endpoints would only require minute adjustments e.g. where fursuit badges are concerned, since those are handled via POST, but otherwise the [target] e.g. for a dealer’s details could just be /Dealers/{id} and accessing said dealer via the web app, one of the native apps or the API would just be as simple as changing the protocol/base URL (e.g. from eurofurence:// to https://app.eurofurence.org/Api/v2/ or https://app.eurofurence.org/web/#/).
All URLs would simply be composable as [client][target] where [client] can (currently) be the web app, the backend or any of the native apps. This would also allow us to, in the future, maybe even integrate with additional services (e.g. a backend management platform).

**Comment by ShezHsky** [comment]
Side-note since this issue's inception: the `apple-app-site-association` file is being hosted on the `app.eurofurence.org` domain, which shows a banner on the pages enabled for deep-linking (e.g. `/EF25/Dealers/<ID>`. The operating system will invoke our application delegate's `-application:continueUserActivity:restorationHandler:` method with a preconfigured user activity for us to digest. This is also the same callback used for the Siri intents.
