### ISSUE TITLE
FCM Routing & Device Registration

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_ios#98]
In order to be able to handle different notification payloads for Android and iOS, please implement the following changes:

1. (Un)Subscribing to topics on **FCM**:

- **Always**  subscribe to the topics `live-all` and `live-ios`
- For **debug/testing** builds (anything that does not resemble the version that non-testers will get from the store), **additionally** subscribe to the topics `test-all` and `test-ios`

2. POSTing the **FcmDeviceRegistration** upsert against the back-end:

- **Always** include the topic `live` and `ios`
- For **debug/testing** builds (anything that does not resemble the version that non-testers will get from the store), **additionally** include the topic `test`
- Feel free to still include the `version-x.x.x.x` tag, and/or any other that may be relevant for your statistics.
- Send the POST request on **every status change of 'login'**, and additionally, on **every start of the application** (later one allows both for cleanup, and for getting actitivity statistics).

Those changes will allow the back-end to reliably route different payloads to Android and iOS consumers, both for broadcasts and individual notifications, and further allows test builds to still consume live notifications and thus be viable for usage during the convention.

**Comment by ShezHsky** [comment]
Keeping a list of the state of what we're sending here, which looks like:

**Firebase Topics**

Debug:
- [x] test-all
- [x] test-ios
- [x] live-all
- [x] live-ios

Release:
- [x] live-all
- [x] live-ios

**FcmDeviceRegistration**

Debug:
- [x] live
- [x] ios
- [x] test
- [x] version-x.x.x

Release:
- [x] live
- [x] ios
- [x] version-x.x.x

**Comment by ShezHsky** [comment]
Updated the topics we registered to in, check 'em out [here](https://github.com/eurofurence/ef-app_ios/blob/9d3555b1ca8b6684f225631e231e7a488bbab249/Eurofurence/Application/Notifications/Firebase/FirebaseRemoteNotificationsTokenRegistration.swift#L28)

**Comment by Pinselohrkater** [comment]
This looks great, thank you! Routing for notifications depending on platform is now [checked in and live](https://github.com/eurofurence/ef-app_backend-dotnet-core/commit/f7c822a81043ecc33fed1e5813ee4db963681858), too.

**Comment by ShezHsky** [comment]
Nice one! Will close this issue for now, if anything needs changing as a result of this work we can spawn a new issue.
